### ISSUE TITLE
Erro de cast ao tentar abrir o sistema

### ISSUE THREAD

**Issue by EduardoPetrini** [rterrabh/TerraER#1]
Ao tentar abrir o Software pela linha de comando no linux ocorre uma exceção de cast (ClassCastException) na linha 259 da classe TerraFigureTree.java. Segue a imagem do bug em anexo.

![terraer](https://cloud.githubusercontent.com/assets/5682887/7289202/ed26cd34-e942-11e4-9d57-5a3c1146c4d3.png)

**Comment by rterrabh** [comment]
Olá Eduardo, obrigado por reportar o erro. Já o corrigi e postei uma versão TerraER2.11 para você.
