### ISSUE TITLE
Start up problem

### ISSUE THREAD

**Issue by massimovrn** [rterrabh/TerraER#2]
Hi!
I'm trying to use your tool, but when I launch the TerraER2.10.jar file the system raises an error, see screenshot attached.

OS: MS Windows 8
Lang: Italian

Cheers,
Massimo
![error](https://cloud.githubusercontent.com/assets/12655963/7878444/eab28abe-05e6-11e5-8b7e-9fa059433a05.png)

**Comment by rterrabh** [comment]
Hi Massimo, problem fixed. Please download the version 2.12 and check it out.
https://github.com/rterrabh/TerraER/blob/master/terraer_project/dist/TerraER2.12.jar
Thanks a lot.

**Comment by massimovrn** [comment]
Great! It's running!
Thak you so much!

Best regards,
Massimo
