### ISSUE TITLE
Exporting a Diagram as an image

### ISSUE THREAD

**Issue by psthodoris** [rterrabh/TerraER#29]
When you are going to save a ER Diagram as an image ,there is not a default image type.As a result if you save it ,just adding a name-file, there is not file format.So,MS-Windows10  does not recognize the file ,as a picture.On the other hand, if you name the file that is going to be exported , as _filename.png_ ,MS-Windows recognize it.
I suggest to add a default image type or name, like "_demo.png_" in order to facilitate beginners users.

![forgit](https://user-images.githubusercontent.com/34039171/33516987-5168a998-d784-11e7-8da9-50b70966f221.png)

**Comment by rterrabh** [comment]
Thanks a lot. I'll fix it for next version.

**Comment by rterrabh** [comment]
Hi terikos. I have just fixed it.

It will be not release yet. Could you test it for me please? I let a beta of next version available at:
https://www.dropbox.com/s/daz75rk3wcnqpl6/TerraER3.12.jar?dl=1

Thanks.

**Comment by psthodoris** [comment]
Hi,
I checked the Beta version you have uploaded.I noticed that this version cannot save the "white" background of the workspace.The image of the diagram in _.png_ format is like the screenshot below:

![tera12](https://user-images.githubusercontent.com/34039171/33609373-7e1316f6-d9d0-11e7-88d8-27496e32ad2c.png)

Also,this problem exists even when I save the image as _.jpeg_ file format.As a result, the connections between entities are not visible.

Thanks for your reply.

**Comment by rterrabh** [comment]
Hi. It is a transparent background. It better in the way it is. Assume you have a yellow background, the picture will be perfect. Assume a gray, it will be perfect. Any color except for black, it will be perfect. Did you get my point?

**Comment by psthodoris** [comment]
Okay, you have a point,it is a feature.
