### ISSUE TITLE
Corrigir validação de generalização/especialização

### ISSUE THREAD

**Issue by iranrodrigues** [rterrabh/TerraER#3]
Atualmente a ferramenta não permite a conexão direta entre uma superclasse e uma subclasse sem o uso da notação de círculo (para denotar disjunção ou sobreposição). Essa possibilidade é válida quando existe apenas uma subclasse, como exemplificado na figura (entidades Football x Prof. Football Player e Professional x Prof. Football Player).

![captura de tela 2015-09-23 as 11 18 26](https://cloud.githubusercontent.com/assets/1478076/10193396/32ba502a-6759-11e5-8cb7-29a854e325d6.png)

(Fonte: Bagui & Earp, 2012).

**Comment by rterrabh** [comment]
Fixed in the release TerraER2.20.
