### ISSUE TITLE
Recursive

### ISSUE THREAD

**Issue by ghost** [rterrabh/TerraER#32]
Is there a way to make a recursive relationship? 
Currently the connections seem to travel from centre to centre.

**Comment by rterrabh** [comment]
Hi. Can you take a look at:
https://github.com/rterrabh/TerraER/blob/master/terraer-example01.mp4
It is a video that explains how to make a recursive relationship.

But, if my mind serves me well, in the last version, if you create a recursive relationship, TerraER automatically adjusts the line position. Can you check this out for me?
