### ISSUE TITLE
Problems on saving project.

### ISSUE THREAD

**Issue by liutuo368** [rterrabh/TerraER#34]
Hi,

When I close the file, it asked me to choose save, not save or cancel. But after I clicked "cancel", I could not save the file any more. The save button became unavaliable.

**Comment by rterrabh** [comment]
It does not occur with me in Mac OS. Which OS are you using?

Perhaps, it is a focus problem, isn't it? After you cancel, click on the drawing and try to save again, just to check it out.

Best regards

**Comment by liutuo368** [comment]
> It does not occur with me in Mac OS. Which OS are you using?
> 
> Perhaps, it is a focus problem, isn't it? After you cancel, click on the drawing and try to save again, just to check it out.
> 
> Best regards

Hi,
After restarting the computer, it didn't happen again. I think it was an accidental event. My OS is ubuntu 19.04

**Comment by rterrabh** [comment]
Okay, perfect. Let me know if it occurs again. Best regards.
