### ISSUE TITLE
Aprimorar suporte a entidades fracas

### ISSUE THREAD

**Issue by iranrodrigues** [rterrabh/TerraER#4]
A ferramenta oferece a possibilidade de inserção de uma entidade fraca. Entretanto, ainda não há suporte à notação de losango duplo para especificar o relacionamento de identificação, nem ao conceito de chave parcial, onde o atributo é representado com seu nome sublinhado com linha tracejada. A figura a seguir ilustra esses conceitos (relacionamento de identificação ED e chave parcial dname):

![captura de tela 2015-09-23 as 11 19 59](https://cloud.githubusercontent.com/assets/1478076/10193842/cf76c04a-675b-11e5-848d-ec149b12c131.png)

(Fonte: Bagui & Earp, 2012)

**Comment by rterrabh** [comment]
Fixed in the release TerraER2.20.
