### ISSUE TITLE
Problemas ao duplicar objetos

### ISSUE THREAD

**Issue by iranrodrigues** [rterrabh/TerraER#5]
Alguns objetos duplicados não mantêm a aparência dos originais. Atributos chave, multivalorados, derivados e chaves parciais ao serem duplicados geram objetos com a aparência de atributos simples. O mesmo ocorre com o relacionamento fraco, que ao ser duplicado gera um relacionamento comum. Um outro ponto a considerar é que o tamanho dos objetos duplicados é bem menor que o tamanho padrão, normalmente requerendo o redimensionamento manual.

Apesar disso, todos mantêm suas regras de validação inalteradas e também são exibidos corretamente no inspetor de objetos.

Esse problema não ocorre se copiarmos e colarmos os objetos ao invés de duplicá-los.

**Comment by rterrabh** [comment]
@iranrodrigues, problema solucionado. Favor testar o Release 2.22 e reabrir caso o erro persista.
